server:
  port: 8090

# mysql_setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain?serverTimezone=Asia/Seoul
    username: parkib002
    password: 1234

  # jsp_setting
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  devtools:
    livereload:
      enabled: true

  # jpa_setting
  jpa:
    hibernate:
      ddl-auto: update  # create: 기존 테이블 삭제 후 생성, update: 변경된 부분만 반영
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
